version: '3.4'

services:
  achieveclub.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5229
      - ASPNETCORE_HTTPS_PORTS=7170
    ports:
      - "5229:5229"
      - "7170:7170"